import { type Metadata } from "next";
import {
  ClerkProvider,
  SignInButton,
  SignUp,
  SignUpButton,
  SignedIn,
  SignedOut,
  UserButton,
} from "@clerk/nextjs";
import { Button } from "@/components/ui/button";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import { syncUser } from "@/actions/user.actions";
import { redirect } from "next/navigation";
import { headers } from "next/headers";
import { NavbarTitle } from "@/components/Navbar/navbar-title";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Clerk Next.js Quickstart",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  await syncUser();

  return (
    <ClerkProvider>
      <html lang="en">
        <body className={`${geistSans.variable} ${geistMono.variable} antialiased relative`}>
          <header className="flex justify-between items-center p-4 gap-4 h-16 bg-gray-800 text-white sticky top-0 z-10">
            <NavbarTitle />
            <div>
              <SignedOut>
                <SignInButton mode="modal">
                  <Button
                    variant="ghost"
                    className="cursor-pointer hover:bg-gray-700 rounded-md p-2 transition"
                  >
                    Sign In
                  </Button>
                </SignInButton>
                <SignUpButton mode="modal" unsafeMetadata={{ role: "PENDING" }}>
                  <Button
                    variant="ghost"
                    className="cursor-pointer hover:bg-gray-700 rounded-md p-2 transition"
                  >
                    Sign Up
                  </Button>
                </SignUpButton>
              </SignedOut>
              <SignedIn>
                <UserButton />
              </SignedIn>
            </div>
          </header>
          {children}
        </body>
      </html>
    </ClerkProvider>
  );
}
